#!/usr/bin/env python3
"""Build Snappix as a single executable file.

One command, the same on every platform - run it on the system the file is
meant for, because PyInstaller cannot build for another one:

    ./build-exe.py              Linux   -> dist/snappix-linux-x86_64-<version>-build<build>
    py build-exe.py             Windows -> dist/snappix-windows-x86_64-<version>-build<build>.exe

What it does:

1. writes the ``VERSION`` file from the commit history (what the post-commit
   hook does in a checkout), because the executable has no history to read,
2. creates a private build environment in ``build/exe/venv`` and installs
   PyInstaller and the pinned packages of ``requirements.txt``,
3. stages the read-only data the program reads next to ``run.py`` - the icons
   and the ``VERSION`` file - under the same relative layout,
4. runs PyInstaller and checks that the result starts.

ffmpeg, Tesseract, xdotool and the other system tools stay outside the file:
Linux takes them from the package manager, Windows installs ffmpeg and
Tesseract per user with ``--install-ffmpeg`` / ``--install-ocr``.
``vendor/ffmpeg-windows.zip`` is deliberately not built in (170 MB).

Options:

    --clean     rebuild the build environment from scratch
    --keep-env  reuse the build environment without updating its packages
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import venv
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src import paths, version  # noqa: E402

BUILD_DIR = ROOT / "build" / "exe"
VENV_DIR = BUILD_DIR / "venv"
STAGE_DIR = BUILD_DIR / "stage"
WORK_DIR = BUILD_DIR / "work"
SPEC_FILE = WORK_DIR / "snappix.spec"
DIST_DIR = ROOT / "dist"

#: Needs 6.9 or newer for ``PYINSTALLER_RESET_ENVIRONMENT``, which the updater
#: sets so a restarted executable unpacks itself afresh.
PYINSTALLER_SPEC = "pyinstaller>=6.9"

#: Read-only files the program opens relative to ``run.py``.
STAGED_DATA = ("assets", version.VERSION_FILE_NAME)

#: Qt modules that are only imported inside functions, plus the ffmpeg
#: downloader the Windows setup imports from ``scripts/``.
HIDDEN_IMPORTS = [
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    "PySide6.QtNetwork",
    "PySide6.QtPrintSupport",
    "PySide6.QtSvg",
    "scripts.fetch_ffmpeg_windows",
]

#: pynput picks its backend by name at run time, so PyInstaller never sees it.
PYNPUT_BACKENDS = {
    "linux": [
        "pynput._util.xorg",
        "pynput._util.xorg_keysyms",
        "pynput._util.uinput",
        "pynput.keyboard._xorg",
        "pynput.keyboard._uinput",
        "pynput.keyboard._dummy",
        "pynput.mouse._xorg",
        "pynput.mouse._dummy",
    ],
    "windows": [
        "pynput._util.win32",
        "pynput._util.win32_vks",
        "pynput.keyboard._win32",
        "pynput.mouse._win32",
    ],
}

SPEC_TEMPLATE = '''# Generated by build-exe.py - edit that script, not this file.
from PyInstaller.utils.hooks import collect_submodules

datas = {datas!r}
hiddenimports = {hidden!r}
for package in {submodules!r}:
    hiddenimports += collect_submodules(package)

a = Analysis(
    [{entry!r}],
    pathex=[{root!r}],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={name!r},
    debug=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    # No console window on Windows; Snappix is a tray application.
    console=False,
    icon={icon!r},
)
'''


def info(message: str) -> None:
    """Print a progress line."""
    print("[build-exe] " + message, flush=True)


def fail(message: str) -> None:
    """Print an error and stop with exit code 1."""
    print("[build-exe] ERROR: " + message, file=sys.stderr, flush=True)
    sys.exit(1)


def venv_python() -> Path:
    """Return the interpreter of the build environment."""
    if paths.is_windows():
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def run(command: List[object], **kwargs) -> None:
    """Run a command and stop the build when it fails."""
    info("$ " + " ".join(str(part) for part in command))
    completed = subprocess.run([str(part) for part in command], **kwargs)
    if completed.returncode != 0:
        fail("command failed with exit code {0}".format(completed.returncode))


def check_build_host() -> None:
    """Stop early when this interpreter cannot produce a working program."""
    if sys.version_info < (3, 11):
        fail("building needs Python 3.11 or newer, like Snappix itself.")
    if not paths.is_linux() and not paths.is_windows():
        fail("Snappix is built for Linux and Windows only.")


def bundled_packages() -> List[str]:
    """Return the pip packages to install into the build environment.

    The pinned lines of ``requirements.txt`` - the same versions a checkout
    installs - plus PyInstaller.  On Linux pip adds pynput's python-xlib and
    evdev by itself.
    """
    packages = [PYINSTALLER_SPEC]
    for raw in (ROOT / "requirements.txt").read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            packages.append(line)
    return packages


def prepare_venv(clean: bool, keep: bool) -> None:
    """Create or refresh the build environment.

    It is created without the system packages, so nothing the build machine
    happens to have installed (numpy, a system PyQt, ...) ends up in the
    executable.
    """
    if clean and VENV_DIR.exists():
        info("Removing the old build environment ...")
        shutil.rmtree(str(VENV_DIR))
    if not venv_python().exists():
        info("Creating the build environment in {0} ...".format(VENV_DIR))
        venv.EnvBuilder(with_pip=True).create(str(VENV_DIR))
    elif keep:
        info("Reusing the build environment as it is.")
        return
    run([venv_python(), "-m", "pip", "install", "--upgrade", "--disable-pip-version-check", "pip"])
    run([venv_python(), "-m", "pip", "install", "--upgrade", "--disable-pip-version-check"]
        + bundled_packages())


def write_version() -> str:
    """Write ``VERSION`` from the history and return the full label.

    The executable reads only this file; a build without a known version would
    ship a program that can never tell whether an update is newer.
    """
    try:
        version.write_version_file(ROOT)
    except OSError as exc:
        fail("could not write {0}: {1}".format(version.VERSION_FILE_NAME, exc))
    name, build = version.version()
    if name == version.UNKNOWN or not build.isdigit():
        fail("the version is unknown - build from a git checkout (CI: fetch-depth 0).")
    return version.version_label()


def stage_data() -> Path:
    """Copy the read-only data the executable carries.

    The layout matches the checkout, so ``_project_root()`` - which is
    ``sys._MEIPASS`` in the executable - finds every file where a checkout has it.

    Returns:
        Path: The staged directory.
    """
    if STAGE_DIR.exists():
        shutil.rmtree(str(STAGE_DIR))
    STAGE_DIR.mkdir(parents=True)
    for name in STAGED_DATA:
        source = ROOT / name
        if source.is_dir():
            shutil.copytree(str(source), str(STAGE_DIR / name))
        elif source.is_file():
            shutil.copy2(str(source), str(STAGE_DIR / name))
        else:
            fail("{0} is missing".format(source))
    info("Staged {0}.".format(", ".join(STAGED_DATA)))
    return STAGE_DIR


def hidden_imports() -> List[str]:
    """Return the modules PyInstaller has to be told about on this platform."""
    return HIDDEN_IMPORTS + PYNPUT_BACKENDS.get(paths.os_family(), [])


def spec_text(staged: Path) -> str:
    """Return the PyInstaller spec file for this platform.

    Args:
        staged: The staged directory from :func:`stage_data`.

    Returns:
        str: The content of the spec file.
    """
    name = paths.executable_name()
    if name.endswith(".exe"):
        name = name[:-4]
    submodules = ["src"]
    if paths.is_linux():
        # python-xlib loads its protocol extensions by name.
        submodules.append("Xlib")
    icon = ROOT / "assets" / "snappix.ico"
    return SPEC_TEMPLATE.format(
        datas=[(str(staged), ".")],
        hidden=hidden_imports(),
        submodules=submodules,
        entry=str(ROOT / "run.py"),
        root=str(ROOT),
        name=name,
        icon=str(icon) if paths.is_windows() and icon.is_file() else None,
    )


def smoke_test(executable: Path, label: str) -> None:
    """Start the result once and make sure it answers."""
    info("Starting {0} --version ...".format(executable.name))
    environment = dict(os.environ)
    # --version answers before Qt is loaded; this only keeps a CI runner
    # without a display safe should that ever change.
    environment.setdefault("QT_QPA_PLATFORM", "offscreen")
    completed = subprocess.run([str(executable), "--version"], stdout=subprocess.PIPE,
                               stderr=subprocess.STDOUT, timeout=300, env=environment)
    output = completed.stdout.decode("utf-8", errors="replace").strip()
    if completed.returncode != 0:
        fail("the executable did not start (exit code {0}):\n{1}".format(completed.returncode, output))
    # A windowed Windows build has no stdout to print to; the exit code has to do.
    expected = version.version_string()
    if output and expected not in output:
        fail("the executable reports {0!r}, expected {1}".format(output, label))
    info("OK: " + (output or "exit code 0"))


def main() -> int:
    """Run the whole build."""
    parser = argparse.ArgumentParser(description="Build Snappix as a single executable file.")
    parser.add_argument("--clean", action="store_true", help="rebuild the build environment from scratch")
    parser.add_argument("--keep-env", action="store_true",
                        help="reuse the build environment without updating its packages")
    args = parser.parse_args()

    check_build_host()
    label = write_version()
    info("Snappix {0} for {1}".format(label, paths.executable_name()))
    prepare_venv(clean=args.clean, keep=args.keep_env)
    staged = stage_data()
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    SPEC_FILE.write_text(spec_text(staged), encoding="utf-8")
    run([venv_python(), "-m", "PyInstaller", "--noconfirm", "--clean",
         "--distpath", DIST_DIR, "--workpath", WORK_DIR, SPEC_FILE], cwd=str(ROOT))

    result = DIST_DIR / paths.executable_name()
    if not result.is_file():
        fail("PyInstaller finished but {0} is missing".format(result))
    smoke_test(result, label)
    info("Done: {0} ({1:.1f} MB)".format(result, result.stat().st_size / 1048576))
    info("This file runs on {0} only; build on the other system for its own file.".format(
        "Windows" if paths.is_windows() else "Linux"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
